spring:
  application:
    name: ai-interview-mcp-server # 应用名称（用于服务发现、日志标识等）
  profiles:
    active: prod
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        sse-endpoint: /sse
        type: async
  mail:
    host: smtp.qq.com            # 邮箱host
    port: 465                      # 邮箱固定端口
    username: 704625068@qq.com
    password: jueljwzhzcsjbcaa
    protocol: smtp                  # 邮箱协议
    default-encoding: UTF-8         # 默认编码
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
# 日志级别
logging:
  level:
    root: info  # # 设置根日志级别为 INFO（输出普通信息）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      banner: false
      update-strategy: not_empty
  mapper-locations: classpath*:/mapper/*.xml
