server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1  # 不限制请求体大小
spring:
  application:
    name: ai-interview # 应用名称（用于服务发现、日志标识等）
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB # 文件上传大小限制
      max-request-size: 10MB  # 文件最大请求限制,可用于批量上传
# 日志级别
logging:
  level:
    root: info  # # 设置根日志级别为 INFO（输出普通信息）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      banner: false
      update-strategy: not_empty
  mapper-locations: classpath*:/mapper/*.xml

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true
