services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "9379:6379"
    volumes:
      - /var/lib/docker/redis-stack/data:/data
    restart: unless-stopped